name: Build Ftx Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-win32:
    name: Build Windows
    runs-on: ubuntu-latest

    container:
      image: willll/windev-docker:v1.0

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create build directory
        run: |
          mkdir buildwin
          cd  buildwin
          export PATH="/opt/mxe-w64/usr/bin/:$PATH"
          x86_64-w64-mingw32.static-cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON
          x86_64-w64-mingw32.static-cmake --build .
          x86_64-w64-mingw32.static-strip ftx.exe -o ../ftx.exe

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ftx.exe
          path: ftx.exe

      - name: Upload executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${GITHUB_REF##*/}/assets
          asset_path: ftx.exe
          asset_name: ftx.exe
          asset_content_type: application/octet-stream
        if: github.ref_type == 'tag'

